Retry-After=HTTP-date/delay-seconds
delay-seconds=1*DIGIT
HTTP-date=IMF-fixdate/obs-date
IMF-fixdate=day-name "," SP date1 SP time-of-day SP GMT
day-name=%s"Mon"/%s"Tue"/%s"Wed"/%s"Thu"/%s"Fri"/%s"Sat"/%s"Sun"
date1=day SP month SP year
day=2DIGIT
month=%s"Jan"/%s"Feb"/%s"Mar"/%s"Apr"/%s"May"/%s"Jun"/%s"Jul"/%s"Aug"/%s"Sep"/%s"Oct"/%s"Nov"/%s"Dec"
year=4DIGIT
time-of-day=hour ":" minute ":" second
hour=2DIGIT
minute=2DIGIT
second=2DIGIT
GMT=%s"GMT"
obs-date=rfc850-date/asctime-date
rfc850-date=day-name-l "," SP date2 SP time-of-day SP GMT
date2=day "-" month "-" 2DIGIT
day-name-l=%s"Monday"/%s"Tuesday"/%s"Wednesday"/%s"Thursday"/%s"Friday"/%s"Saturday"/%s"Sunday"
asctime-date=day-name SP date3 SP time-of-day SP year
date3=month SP (2DIGIT/SP DIGIT)
