root=Strict-Transport-Security
Strict-Transport-Security = [ directive ] *( *LWS ";" *LWS [ directive ] )
directive = directive-name *LWS [ "=" *LWS directive-value *LWS ]
LWS = [CRLF] 1*(SP/HTAB)
directive-name = token
directive-value = token/quoted-string
token=1*tchar
tchar="!"/"#"/"$"/"%"/"&"/"'"/"*"/"+"/"-"/"."/"^"/"_"/"`"/"|"/"~"/DIGIT/ALPHA
quoted-string=DQUOTE *(qdtext/quoted-pair) DQUOTE
qdtext=HTAB/SP/%x21/%x23-5B/%x5D-7E
quoted-pair="\" (HTAB/SP/VCHAR)

